development:
   AWS_ACCESS_KEY_ID: 'AKIAULHC2IOLAEXWFDDV'
   AWS_SECRET_ACCESS_KEY: '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'
   S3_BUCKET: 'space-home'
test:
   AWS_ACCESS_KEY_ID: 'AKIAULHC2IOLAEXWFDDV'
   AWS_SECRET_ACCESS_KEY: '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'
   S3_BUCKET: 'space-home-test'
production:
   AWS_ACCESS_KEY_ID: 'AKIAULHC2IOLAEXWFDDV'
   AWS_SECRET_ACCESS_KEY: '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'
   S3_BUCKET: 'space-home-production'
